# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getloglike <- function(pmats, path, y) {
    .Call('dpf_getloglike', PACKAGE = 'dpf', pmats, path, y)
}

yupengMats <- function(lt, temposwitch, sig2eps, mus, sig2eta, transprobs) {
    .Call('dpf_yupengMats', PACKAGE = 'dpf', lt, temposwitch, sig2eps, mus, sig2eta, transprobs)
}

beamSearch <- function(a0, P0, w0, dt, ct, Tt, Zt, Rt, Qt, GGt, yt, transProbs, N) {
    .Call('dpf_beamSearch', PACKAGE = 'dpf', a0, P0, w0, dt, ct, Tt, Zt, Rt, Qt, GGt, yt, transProbs, N)
}

rcpparma_hello_world <- function() {
    .Call('dpf_rcpparma_hello_world', PACKAGE = 'dpf')
}

rcpparma_outerproduct <- function(x) {
    .Call('dpf_rcpparma_outerproduct', PACKAGE = 'dpf', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('dpf_rcpparma_innerproduct', PACKAGE = 'dpf', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('dpf_rcpparma_bothproducts', PACKAGE = 'dpf', x)
}

